SLCORE-413 Add client method to list all taint vulnerabilities for a project
SonarSource/sonarlint-core pull request #523
Opened 2022-10-28 09:45 UTC by jblievremont

2022-11-02 10:24 UTC, henryju reviewed
I don't think this is the good way to use Xodus. It would be better to add a new link between branch and taint issues, to avoid involving the file entity. This would require a migration, and this is not something we have done yet.

2022-11-02 14:33 UTC, jblievremont commented
I'm wondering whether a migration would be necessary, or "just" invalidation + re-sync.

2022-11-03 17:14 UTC, henryju requested changes
LGTM, with a few comments.
I think a test is missing: if I'm correct the specific migration v0 -> v1 is not tested. We could maybe have a medium test. Not sure how to produce the "old" DB. I think we should avoid storing binaries as test resources, so maybe you could create the "old" DB programmatically. Or maybe: create a new DB, then revert the schema version to zero, reopen the DB, and check that all last sync timestamps have been reset to zero.

2022-11-03 17:14 UTC, henryju commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +      txn.findWithProp(BRANCH_ENTITY_TYPE, NAME_PROPERTY_NAME).forEach(b -> b.setProperty(LAST_TAINT_SYNC_PROPERTY_NAME, Instant.EPOCH));
What is the point of `findWithProp` here? Why not simply `getAll`?

2022-11-03 17:14 UTC, henryju commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +      txn.findWithProp(SCHEMA_ENTITY_TYPE, VERSION_PROPERTY_NAME).forEach(Entity::delete);
Same, I would use `getAll`

2022-11-03 17:14 UTC, henryju commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +    var schemaEntities = txn.findWithProp(SCHEMA_ENTITY_TYPE, VERSION_PROPERTY_NAME);
Same, I would use `getAll`

2022-11-07 08:06 UTC, sophio-japharidze-sonarsource commented on core/src/main/java/org/sonarsource/sonarlint/core/client/api/connected/ConnectedSonarLintEngine.java
> +   */
I think this annotation needs to be updated? `serverPathToIdePath` is an extra `@param`, and the description - If I understood correctly this method gets all server taint issues for a branch (not the given _file_).

2022-11-07 09:28 UTC, sophio-japharidze-sonarsource approved these changes

2022-11-07 12:10 UTC, henryju approved these changes

2022-11-07 15:18 UTC, merged