SLCORE-429 Manage the embedded server from the new backend
SonarSource/sonarlint-core pull request #546
Opened 2022-12-19 12:14 UTC by damien-urruty-sonarsource

2022-12-20 10:03 UTC, henryju requested changes
Some comments, but most of it LGTM. I'm eager to see it used in all IDEs :)

2022-12-23 14:37 UTC, damien-urruty-sonarsource commented on client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/SonarLintClient.java
> +  HttpClient getHttpClient(@Nullable String connectionId);
Yes good idea

2022-12-23 14:40 UTC, damien-urruty-sonarsource commented on core/src/main/java/org/sonarsource/sonarlint/core/AuthenticationHelperServiceImpl.java
> +    CompletableFuture.runAsync(() -> {
I don't think using `supplyAsync` would help here, this method takes a Supplier, and we wouldn't not be able to supply the token immediately. That's why I create a separate future that will be resolved later when we receive the token

2022-12-23 14:44 UTC, damien-urruty-sonarsource commented on core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/AwaitingUserTokenFutureRepository.java
> +    this.futureResponse = Optional.of(futureResponse);
Probably setting a new future should cancel a previous one. And yes for the reference

2023-01-03 13:50 UTC, henryju approved these changes
Well done! LGTM!

2023-01-12 15:56 UTC, henryju approved these changes

2023-01-16 08:07 UTC, merged