SLCORE-509 Pull existing issues when a new language is enabled
SonarSource/sonarlint-core pull request #667
Opened 2023-07-24 08:02 UTC by eray-felek-sonarsource

2023-07-25 16:08 UTC, henryju requested changes
I think there are still a few improvements to do, but overall that looks very good to me. Please ask @thahnen to give it another look before merging!

2023-07-26 09:14 UTC, eray-felek-sonarsource commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +  public Optional<String> getLastIssueEnabledLanguages(String branchName) {
I think it is even better if it is Set<String> so that we avoid converting it to it since its use case will be only Set<String>

2023-07-26 10:17 UTC, thahnen requested changes
Hi @eray-felek-sonarsource,

a lot of suggestions from my side, sorry ^^
The mixture of `Set<String>` and `Set<Language>` is the biggest issue in my opinion as it brings a lot of overhead and complexity.

The other stuff not directly related is QOL stuff but fixing that is much appreciated!

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +  @NotNull
Cannot be `null`, remove this please.

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/UpdaterUtils.java
> +  public static Optional<Instant> computeLastSync(Set<Language> enabledLanguages, Optional<Instant> lastSync, Set<String> lastEnabledLanguages) {
Please do not mix `Set<Language>` and `Set<String>`, stick everywhere with `Set<Language>`. Then the conversion to `enabledLanguageSet` is not needed.

Also, provide some Javadoc and change the name: The message computes no synchronization information but rather modifies it if the languages do not match.

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/UpdaterUtils.java
> +public class UpdaterUtils {
Change the class name to `ServerUpdaterUtils` please, as the impacted classes follow the `Server*Updater` name pattern.

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ProjectServerIssueStore.java
> +  void mergeIssues(String branchName, List<ServerIssue> issuesToMerge, Set<String> closedIssueKeysToDelete, Instant syncTimestam, Set<Language> enabledLanguages);
`syncTimestamp` lost its `p`, please bring it back 😄

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ProjectServerIssueStore.java
> +  Set<String> getLastIssueEnabledLanguages(String branchName);
As mentioned above, move this to `Set<Language>` to be consistent, also for `getLastTaintEnabledLanguages` and `getLastHotspotEnabledLanguages`

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/StorageUtils.java
> +  public static Set<String> deserializeLanguages(Optional<String> lastEnabledLanguages) {
Change this to `Set<Language>` in order with the other changes. Also, add Javadoc, I currently don't get where it is deserialized from.

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreMigrationTests.java
> +import static org.mockito.ArgumentMatchers.any;
These static imports seem to be not used in the changes proposed, please remove them if not used.

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java
> +    var lastEnabledLanguages = store.getLastIssueEnabledLanguages("branch");
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java
> +    var lastEnabledLanguages = store.getLastHotspotEnabledLanguages("branch");
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java
> +    var lastEnabledLanguages = store.getLastTaintEnabledLanguages("branch");
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    String serializedLanguages = getSerializedLanguages(enabledLanguages);
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    String serializedLanguages = getSerializedLanguages(enabledLanguages);
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    String serializedLanguages = getSerializedLanguages(enabledLanguages);
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    var serializedLanguages = languagesList.stream().map(Language::getLanguageKey)
remove this variable by directly returning it

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    var lastEnabledLanguages = ofNullable(lastIssueEnabledLanguagesByBranch.get(branchName));
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    var lastEnabledLanguages = ofNullable(lastTaintEnabledLanguagesByBranch.get(branchName));
inline this variable directly

2023-07-26 10:17 UTC, thahnen commented on server-connection/src/test/java/testutils/InMemoryIssueStore.java
> +    var lastEnabledLanguages = ofNullable(lastHotspotEnabledLanguagesByBranch.get(branchName));
inline this variable directly

2023-07-26 14:30 UTC, thahnen approved these changes
Looks good, please take a look at the remaining SQ issues and try to fix most of them (some of them you already mentioned are false-positives).

2023-07-27 09:18 UTC, merged