Task/vs/slcore 495 manage telemetry from core
SonarSource/sonarlint-core pull request #781
Opened 2023-11-15 13:32 UTC by vojtech-suchy-sonarsource

2023-11-20 07:35 UTC, henryju reviewed
I made already a few comments last week, but now the PR needs to be rebased, this would make the review easier.

2023-11-20 16:03 UTC, henryju requested changes

2023-11-20 19:10 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryLiveAttributesResponse.java
> +  public boolean isUsesConnectedMode() {
Now reported in https://sonarsource.atlassian.net/browse/SLCORE-628

2023-11-20 19:10 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryLiveAttributesResponse.java
> +  public boolean isUseSonarCloud() {
Now reported in https://sonarsource.atlassian.net/browse/SLCORE-628

2023-11-20 19:10 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryLiveAttributesResponse.java
> +  public boolean isDevNotificationsDisabled() {
Now reported in https://sonarsource.atlassian.net/browse/SLCORE-628

2023-11-20 19:10 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryLiveAttributesResponse.java
> +  public List<String> getNonDefaultEnabledRules() {
Now reported in https://sonarsource.atlassian.net/browse/SLCORE-628

2023-11-20 19:10 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryLiveAttributesResponse.java
> +  public List<String> getDefaultDisabledRules() {
Now reported in https://sonarsource.atlassian.net/browse/SLCORE-628

2023-11-20 19:11 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java
> +  void stop();
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:11 UTC, vojtech-suchy-sonarsource commented on rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/AddQuickFixAppliedForRule.java
> +public class AddQuickFixAppliedForRule {
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java
> +    var clientTelemetryPayload = getTelemetryLiveAttributes();
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java
> +    var clientTelemetryPayload = getTelemetryLiveAttributes();
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java
> +    var clientTelemetryPayload = getTelemetryLiveAttributes();
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
> +    var telemetryPayload = new TelemetryLiveAttributesResponse(true, false, null, false, emptyList(), emptyList(), emptyMap());
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
> +    var telemetryPayload = new TelemetryLiveAttributesResponse(true, false, null, false, emptyList(), emptyList(), emptyMap());
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-20 19:12 UTC, vojtech-suchy-sonarsource commented on telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
> +    var telemetryPayload = new TelemetryLiveAttributesResponse(true, false, null, false, emptyList(), emptyList(), emptyMap());
Addressed in [a63d13f](https://github.com/SonarSource/sonarlint-core/pull/781/commits/a63d13f315ca41eab6710a91422be3ecc0574b85)

2023-11-21 07:43 UTC, henryju approved these changes
Well done!

2023-11-21 07:54 UTC, merged