SLCORE-631 Stop asking client to manipulate server file paths
SonarSource/sonarlint-core pull request #823
Opened 2023-12-15 14:20 UTC by kirill-knize-sonarsource

2023-12-22 13:04 UTC, henryju requested changes
Good work overall. I don't think I will have time for an in-depth review, so I left a few comments already, and then please ask another review from @damien-urruty-sonarsource before merging (or Damien can merge next week).
I am not sure about the need for the retry mechanism in the Path translation service. I think it could be a separate task if we feel the need.

2023-12-22 13:04 UTC, henryju commented on backend/core/src/test/java/org/sonarsource/sonarlint/core/file/PathTranslationServiceTests.java
> +class PathTranslationServiceTests {
Shouldn't you test the retry mechanism?

2023-12-22 13:04 UTC, henryju commented on backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
> +      .filter(e -> path.equals(Path.of((String) e.getProperty(propertyName))))
:+1:

2023-12-29 14:34 UTC, damien-urruty-sonarsource approved these changes
One small comment, else LGTM

2024-01-02 05:29 UTC, merged